[package]
name = "btr"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
chrono = { version = "0.4.42", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.5"
serde_json = "1.0.143"
